const initialCarsState = {
    cars : [
        {
          id: 1,
          photos: [
            "https://ireland.apollo.olxcdn.com/v1/files/bg0wzju6uc3x1-UA/image;s=1000x700",
            "https://ireland.apollo.olxcdn.com/v1/files/d2qvny4thsfb3-UA/image;s=1000x700",
          ],
          brand: "Audi",
          model: "Q7",
          modification: "S-line Quattro",
          customsCleared: "Так",
          mileage: 156,
          price: 67999,
          engineVolume: 3.0,
          fuelConsumption: "6",
          year: 2020,
          fuelType: "Дизель",
          transmission: "Типтронік",
          color: "Білий",
          bodyType: "Позашляховик/Кроссовер",
          driveType: "Повний",
          numberSeats: 7,
          technicalCondition:
            "Гаражне зберігання, Не фарбована, Не бита, Сервісна книжка, Перший власник",
          comfort:
            "Шкіряний салон, Бортовий комп'ютер, Парктроник, Тонування скла, Електросклопiдйомники, Клiмат контроль, Омивач фар, Кондиціонер, Датчик світла, Запуск кнопкою, Підсилювач керма, Обігрів керма, Ел. регулювання сидінь, Мультируль, Підігрів дзеркал, Передня камера, Електропакет, Круїз контроль, Підігрів сидінь, Датчик дощу, Пам'ять сидінь",
          multimedia:
            "Акустика, AUX, Система навігації GPS, Сабвуфер, Підсилювач, Android Auto, Магнітола, Bluetooth, USB",
          security:
            "Лазерні фари, Безключовий доступ, Сигналізація, Пневмопідвіска, Сервокермо, ESP, ABS, Денні ходові вогні, ABD, Центральний замок, Іммобілайзер, LED фари, Подушка безпеки (Airbag), GPS трекер",
          description:
            "Німецький преміальний 7-містний позашляховик в S-line. Двигун 3.0 літра дизель, повний привід Quattro. Авто в ідеалі по зовнішньому, внутрішньому та технічному стані. Пробіг рідний, жодна деталь не фарбована. Колір білий перламутр. Пройшла повне обслуговування на офіційній станції, жодних вкладень не потребує.",
          location: "Ужгород",
          datePublication: "25 липня 2024р.",
          owner: "Валерій",
          phone: "09876543210"
        },
        {
          id: 2,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/k2cfxle7rcok3-UA/image;s=1000x700", 
              "https://ireland.apollo.olxcdn.com/v1/files/pz8r6gjb3n901-UA/image;s=1000x700"
          ],
          brand: "Chevrolet",
          model: "Camaro",
          modification: "ZL1",
          customsCleared: "Ні",
          mileage: 56,
          price: 18500,
          engineVolume: 6.2,
          fuelConsumption: "-",
          year: 2019,
          fuelType: "Бензин",
          transmission: "Автоматична",
          color: "Чорний",
          bodyType: "Купе",
          driveType: "Задній",
          numberSeats: 4,
          technicalCondition: "На ходу, технічно справна",
          comfort: "Електропакет, Електросклопiдйомники, Кондиціонер, Парктроник, Бортовий комп'ютер, Запуск кнопкою, Клiмат контроль, Шкіряний салон, Круїз контроль, Мультируль, Обігрів керма, Підсилювач керма, Підігрів сидінь, Ел. регулювання сидінь, Камера заднього виду",
          multimedia: "Bluetooth, Система навігації GPS",
          security: "ABD, ABS, ESP, Подушка безпеки (Airbag), Центральний замок",
          description: "Телефонуйте та бронюйте для себе дане авто з економією більше ніж 30% в порівняні з ринком в Україні. Повна перевірка авто та огляд автоексперта є присутніми. Авто в хорошому технічному стані та чистою історією.",
          location: "Київ, Голосіївський",
          datePublication: "5 серпня 2024р.",
          owner: "Сергій",
          phone: "09876543210"
        },
        {
          id: 3,
          photos: [
            "https://ireland.apollo.olxcdn.com/v1/files/wtlnkaer6fjb-UA/image;s=1000x700",
            "https://ireland.apollo.olxcdn.com/v1/files/7m92vjnicqvm3-UA/image;s=1000x700",
          ],
          brand: "Nissan",
          model: "X-Trail",
          modification: " Т 30",
          customsCleared: "Ні",
          mileage: 215,
          price: 4300,
          engineVolume: 2.2,
          fuelConsumption: "7",
          year: 2001,
          fuelType: "Дизель",
          transmission: "Механічна",
          color: "Чорний",
          bodyType: "Позашляховик/Кроссовер",
          driveType: "Повний",
          numberSeats: 5,
          technicalCondition: "Технічно справний",
          comfort: "Мультируль, Електросклопiдйомники, Панорамний дах, Тонування скла, Кондиціонер, Підсилювач керма, Підігрів дзеркал, Клiмат контроль, Люк, Електропакет",
          multimedia: "CD, AUX, Магнітола, Bluetooth, Акустика, USB",
          security: "ESP, Подушка безпеки (Airbag), Центральний замок, ABS",
          description: "Автомобіль можливо придбати для потреб ЗСУ.Авто в наявності в Польщі.\nАвто в дуже доглянутому стані і збереженому як косметичному так і технічному стані, все справне, а також проведені технічні роботи по заміні необхідних матеріалів ! Кузов у автомобіля без іржі ( пороги, стакани, арки, днище і т.д. все в доброму стані)\nNissan X-Trail Т30 4х4 повний привід з блокуванням, 2001 року з двигуном 2.2 турбо-дизель на 6-ст механіці. Оригінальний пробіг 246тис.км. Авто доглянуте та підготовлено технічно.",
          location: "Київ",
          datePublication: "4 серпня 2024р.",
          owner: "Володя",
          phone: "09876543210"
        },
        {
          id: 4,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/leqzmsa2v3pn-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/7yxfsbtpt7qi3-UA/image;s=1000x700"
          ],
          brand: "Nissan",
          model: "GT-R",
          modification: "Premium",
          customsCleared: "Ні",
          mileage: 50,
          price: 35000,
          engineVolume: 3.8,
          fuelConsumption: "12",
          year: 2015,
          fuelType: "Бензин",
          transmission: "Автоматична",
          color: "Чорний",
          bodyType: "Купе",
          driveType: "Повний",
          numberSeats: 4,
          technicalCondition: "На ходу, технічно справна",
          comfort: "Кондиціонер, Алькантара, Клiмат контроль, Круїз контроль, Електропакет, Електросклопiдйомники, Ел. регулювання сидінь, Передня камера, Підігрів сидінь, Шкіряний салон, Мультируль, Бортовий комп'ютер, Парктроник, Підсилювач керма, Камера заднього виду, Пам'ять сидінь, Запуск кнопкою",
          multimedia: "Android Auto, Apple CarPlay, AUX, Bluetooth, Система навігації GPS, USB",
          security: "ABS, Подушка безпеки (Airbag), Центральний замок, ESP, Безключовий доступ, LED фари",
          description: "Авто від страхової компанії!",
          location: "Вінниця",
          datePublication: "29 липня 2024р.",
          owner: "Роман",
          phone: "09876543210"
        },
        {
          id: 5,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/v92a3iwwt9c63-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/gqyc97z27pu62-UA/image;s=1000x700"
          ],
          brand: "Audi",
          model: "A4",
          modification: "B8",
          customsCleared: "Так",
          mileage: 287,
          price: 8200,
          engineVolume: 2.0,
          fuelConsumption: "7.5",
          year: 2009,
          fuelType: "Бензин",
          transmission: "Механічна",
          color: "Чорний",
          bodyType: "Універсал",
          driveType: "Передній",
          numberSeats: 5,
          technicalCondition: "Сервісна книжка, Не бита, Не фарбована, На ходу, технічно справна",
          comfort: "Підсилювач керма, Круїз контроль, Електропакет, Датчик дощу, Електросклопiдйомники, Підігрів сидінь, Запуск кнопкою, Датчик світла, Мультируль, Кондиціонер, Бортовий комп'ютер, Клiмат контроль, Парктроник",
          multimedia: "Bluetooth, Підсилювач, Система навігації GPS, AUX, Акустика, Магнітола",
          security: "Денні ходові вогні, Подушка безпеки (Airbag), ESP, Центральний замок, ABS, Іммобілайзер",
          description: "Пропоную до продажу Audi A4 B8 2.0 TFSI, привезену з Німеччини для власного користування. Автомобіль не брав участі в ДТП, знаходиться у відмінному технічному стані.\nЗамінено ланцюг ГРМ, гальмівні колодки. Відремонтована підвіска. В комплекті зимова резина.\nЛобове скло має тріщину.\nАвтомобіль вартий вашої уваги! За більш детальною інформацією та для огляду звертайтесь за телефоном.",
          location: "Івано-Франківськ",
          datePublication: "2 серпня 2024р.",
          owner: "Владислав",
          phone: "09876543210"
        },
        {
          id: 6,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/bf1aoyxp3cc12-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/6m555u7d775i2-UA/image;s=1000x700"
          ],
          brand: "Toyota",
          model: "Tundra",
          modification: "4.6 V8",
          customsCleared: "Так",
          mileage: 173,
          price: 22800,
          engineVolume: 4.6,
          fuelConsumption: "20",
          year: 2014,
          fuelType: "Газ/Бензин",
          transmission: "Автоматична",
          color: "Сірий",
          bodyType: "Пікап",
          driveType: "Задній",
          numberSeats: 5,
          technicalCondition: "На ходу, технічно справна",
          comfort: "-",
          multimedia: "-",
          security: "-",
          description: "-",
          location: "Рівне",
          datePublication: "30 липня 2024р.",
          owner: "Олег",
          phone: "09876543210"
        },
        {
          id: 7,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/bqdgiunftcrs-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/n2iudcocb6tj3-UA/image;s=1000x700"
          ],
          brand: "Scion",
          model: "FR-S",
          modification: "-",
          customsCleared: "Так",
          mileage: 104,
          price: 13999,
          engineVolume: 2.0,
          fuelConsumption: "9",
          year: 2015,
          fuelType: "Бензин",
          transmission: "Автоматична",
          color: "Білий",
          bodyType: "Купе",
          driveType: "Задній",
          numberSeats: 4,
          technicalCondition: "На ходу, технічно справна",
          comfort: "Бортовий комп'ютер, Електросклопiдйомники, Підсилювач керма, Тонування скла, Кондиціонер, Підігрів дзеркал, Алькантара, Датчик світла, Круїз контроль",
          multimedia: "Магнітола, Bluetooth, USB, Система навігації GPS, AUX",
          security: "Сигналізація, Денні ходові вогні, Ксенон, ESP, ABS, Іммобілайзер, Подушка безпеки (Airbag), LED фари, Центральний замок",
          description: "Продам Scion FR-S ( Toyota GT 86, Subaru BRZ) 2015року з надійною автоматичною коробкою та атмосферних двигуном 2л який видає 200кс. Машина візуально та технічно в ідеальному стані. На авто встановленні дуже рідкісні диски R18 Ronal Aero 18 та літня гума Uniroyal Rain Sport. Встановлений оригінальний спойлер. Повністю обслужена гальмівна система з новими колодками, та пофарбовані суппорта в гарний золотистий колір. В авто є підрулеві пелюстки перемикання передач. Мультимедійна система з сенсорним дисплеєм та Bluetooth. Лінзовані фари з лед лампами та функцією автосвітла. 500 км назад замінені всі фільтра та мастило в двигуні. Перевірена система кондиціонування. Авто дарує незабутні емоції, викликає на дорогах захват оточуючих та привертає увагу!!!",
          location: "Київ, Святошинський",
          datePublication: "17 липня 2024р.",
          owner: "Михайло",
          phone: "09876543210"
        },
        {
          id: 8,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/jtaf77o0c4ms-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/ipkqgriy4ont3-UA/image;s=1000x700"
          ],
          brand: "Mazda",
          model: "323",
          modification: "-",
          customsCleared: "Так",
          mileage: 260,
          price: 1900,
          engineVolume: 1.5,
          fuelConsumption: "7",
          year: 1996,
          fuelType: "Газ/Бензин",
          transmission: "Механічна",
          color: "Сірий",
          bodyType: "Седан",
          driveType: "Передній",
          numberSeats: 5,
          technicalCondition: "На ходу, технічно справна",
          comfort: "Електросклопiдйомники, Підсилювач керма, Тонування скла, Мультируль, Бортовий комп'ютер, Кондиціонер",
          multimedia: "Магнітола, Bluetooth, AUX",
          security: "-",
          description: "Авто на ходу з незначними нюансами по ЛКП. Мотор та коробка працюють без нарікань. Новий радіатор на охолодження та помпа. Було замінено повністю комплект щеплення та пів року тому циліндрики. Приємний розхід палива: 8-9 літрів газу по місту, можна вкластись в 7 по трасі. Виведений борт комп'ютер на панель. Робочі склопідйомники в круг. Електрорегулювання дзеркал. Кондиціонер працює, потрібно лише заправити. Заводські велюрові сидіння від рекаро та мульти кермо.",
          location: "Рівне",
          datePublication: "18 липня 2024р.",
          owner: "Богдан",
          phone: "09876543210"
        },
        {
          id: 9,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/8sno08xmt9wj1-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/lailed5k8b991-UA/image;s=1000x700"
          ],
          brand: "Volkswagen",
          model: "Passat",
          modification: "gbo 4",
          customsCleared: "Так",
          mileage: 260,
          price: 9350,
          engineVolume: 2.5,
          fuelConsumption: "9",
          year: 2012,
          fuelType: "Бензин",
          transmission: "Автоматична",
          color: "Сірий",
          bodyType: "Седан",
          driveType: "Передній",
          numberSeats: 5,
          technicalCondition: "Гаражне зберігання, На ходу, технічно справна",
          comfort: "Електросклопiдйомники, Клiмат контроль, Кондиціонер, Круїз контроль, Бортовий комп'ютер, Мультируль, Датчик світла, Електропакет, Підсилювач керма",
          multimedia: "Акустика, Bluetooth, AUX",
          security: "Центральний замок, ESP, Сигналізація, ABS, Сервокермо, Денні ходові вогні, Подушка безпеки (Airbag)",
          description: "Автомобіль у чудовому стані. Повністю обслужений та справний. У експлуатації досить комфортний та економний авто. Росхід газу за містом складає до 9 л/100км. Інші питання за телефоном.",
          location: "Хмельницький",
          datePublication: "4 серпня 2024р.",
          owner: "Саша",
          phone: "09876543210"
        },
        {
          id: 10,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/dzhln9nf9cst2-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/eukwfw2ypg682-UA/image;s=1000x700"
          ],
          brand: "Mercedes",
          model: "SL",
          modification: "450",
          customsCleared: "Так",
          mileage: 63,
          price: 59900,
          engineVolume: 3.0,
          fuelConsumption: "-",
          year: 2017,
          fuelType: "Бензин",
          transmission: "Автоматична",
          color: "Синій",
          bodyType: "Кабріолет",
          driveType: "Задній",
          numberSeats: 2,
          technicalCondition: " На ходу, технічно справна, Гаражне зберігання",
          comfort: "Електропакет, Електросклопiдйомники, Парктроник, Бортовий комп'ютер, Датчик світла, Запуск кнопкою, Клiмат контроль, Шкіряний салон, Круїз контроль, Люк, Мультируль, Підігрів дзеркал, Підсилювач керма, Підігрів сидінь, Тонування скла, Пам'ять сидінь, Датчик дощу, Ел. регулювання сидінь, Камера заднього виду",
          multimedia: "CD, AUX, Bluetooth, USB, Акустика, Магнітола, Підсилювач, Сабвуфер, Система навігації GPS, Apple CarPlay, Android Auto",
          security: "ABD, ABS, ESP, Іммобілайзер, Подушка безпеки (Airbag), Сервокермо, Центральний замок, LED фари, Безключовий доступ",
          description: "Mercedes-Benz SL «Designo Edition» - лімітована версія в кузові родстер. У пакет входять спеціальні 19-дюймові передні та 20-дюймові задні ковані диски AMG з 10-ти спицями, обробка салону з білої шкіри наппа, мультиконтурні сидіння, білі ремені безпеки й чорно-біле шкіряне трьох спицеве кермо. Кузов автомобіля в даній версії в ексклюзивному кольорі діамантово синій металік (Brilliant Blue Metallic). Кліматизовані сидіння з підігрівом на рівні шиї AIRSCARF та пакет сидінь Multicontour Seat з підігрівом та вентиляцією. Інтерʼєр салону виконаний ексклюзивними елементами дизайну та високоякісними матеріалами. Крім того, в оснащення автомобіля входить безліч додаткових систем безпеки та допомоги водієві: пакет «Driving Assistance» з круїз-контролем DISTRONIC, гальмівний асистент Active Brake Assist з функцією аналізу дорожнього трафіку, контроль сліпих зон Active Blind Spot Assist, система контролю смуги Active Lane Keeping Assist i комплексна технологія безпеки PRE-SAFE PLUS. Пакет SL «Designo Edition» в даному варіанті з допрацьованою електронікою, збільшена потужність авто до 430 к.с.неймовірна динаміка зі звучанням спорт вихлопа атд.",
          location: "Київ",
          datePublication: "4 серпня 2024р.",
          owner: "Оксана",
          phone: "09876543210"
        },
        {
          id: 11,
          photos: [
              "https://ireland.apollo.olxcdn.com/v1/files/nr7lcs9t4rpu2-UA/image;s=1000x700",
              "https://ireland.apollo.olxcdn.com/v1/files/rga6fxhdoykv2-UA/image;s=1000x700"
          ],
          brand: "Audi",
          model: "RS6",
          modification: "4.0 TFSI",
          customsCleared: "Так",
          mileage: 113,
          price: 59999,
          engineVolume: 4.0,
          fuelConsumption: "20",
          year: 2016,
          fuelType: "Бензин",
          transmission: "Автоматична",
          color: "Синій",
          bodyType: "Універсал",
          driveType: "Повний",
          numberSeats: 5,
          technicalCondition: "Сервісна книжка, Не бита, Не фарбована, Гаражне зберігання",
          comfort: "-",
          multimedia: "Сабвуфер, Apple CarPlay, USB, AUX, Акустика, Система навігації GPS, Підсилювач, Магнітола, Android Auto",
          security: "LED фари, Подушка безпеки (Airbag), Центральний замок, Замок на КПП, Денні ходові вогні, Сервокермо, ESP, Галогенні фари, Сигналізація, Іммобілайзер, ABD, Безключовий доступ, Ксенон, ABS, Лазерні фари",
          description: "Офіційний автомобіль! Без ДТП. Рідний пробіг підтверджений на СТО. Додатково встановлений вихлоп Miltek. Охолодження повітря - повітря. Автомобіль повністю покритий керамікою та зберігається у теплому паркінгу! два комплекти гуми. Технічно справна та не потребує вкладень. ТО кожні 4 тис км., паливо виключно 100 бензин.",
          location: "Коцюбинське, Київська обл.",
          datePublication: "21 липня 2024р.",
          owner: "Марик",
          phone: "09876543210"
        }
      ]
}
export const CarsMainPageReducer = (state = initialCarsState, action) => {
    switch (action.type) {
      case "ADD_CARS":
        return { ...state,
          cars: [...state.cars, ...action.payload],};
      case "DELETE_CAR":
      return {
        ...state,
        cars: state.cars.filter((car) => car.id != action.payload),
      };
      default:
        return state;
    }
  };